// https://edabit.com/challenge/9kTgWLWEgpqRKakoy

// confused - walk away
const annaLikes = (boy) => {
  return boy.length;
};

// Tests

console.log(annaLikes('James'), false); // Test 1
console.log(annaLikes('John'), false); // Test 2
console.log(annaLikes('Robert'), false); // Test 3
console.log(annaLikes('Michael'), false); // Test 4
console.log(annaLikes('William'), false); // Test 5
console.log(annaLikes('David'), false); // Test 6
console.log(annaLikes('Richard'), false); // Test 7
console.log(annaLikes('Joseph'), false); // Test 8
console.log(annaLikes('Thomas'), false); // Test 9
console.log(annaLikes('Charles'), false); // Test 10
console.log(annaLikes('Christopher'), false); // Test 11
console.log(annaLikes('Daniel'), true); // Test 12
console.log(annaLikes('Matthew'), false); // Test 13
console.log(annaLikes('Anthony'), false); // Test 14
console.log(annaLikes('Donald'), false); // Test 15
console.log(annaLikes('Mark'), false); // Test 16
console.log(annaLikes('Paul'), true); // Test 17
console.log(annaLikes('Steven'), false); // Test 18
console.log(annaLikes('Andrew'), false); // Test 19
console.log(annaLikes('Kenneth'), false); // Test 20
console.log(annaLikes('Joshua'), true); // Test 21
console.log(annaLikes('Kevin'), false); // Test 22
console.log(annaLikes('Brian'), false); // Test 23
console.log(annaLikes('George'), true); // Test 24
console.log(annaLikes('Edward'), false); // Test 25
console.log(annaLikes('Ronald'), false); // Test 26
console.log(annaLikes('Timothy'), false); // Test 27
console.log(annaLikes('Jason'), false); // Test 28
console.log(annaLikes('Jeffrey'), false); // Test 29
console.log(annaLikes('Ryan'), false); // Test 30
console.log(annaLikes('Jacob'), false); // Test 31
console.log(annaLikes('Gary'), false); // Test 32
console.log(annaLikes('Nicholas'), false); // Test 33
console.log(annaLikes('Eric'), true); // Test 34
console.log(annaLikes('Jonathan'), false); // Test 35
console.log(annaLikes('Stephen'), false); // Test 36
console.log(annaLikes('Larry'), false); // Test 37
console.log(annaLikes('Justin'), false); // Test 38
console.log(annaLikes('Scott'), false); // Test 39
console.log(annaLikes('Brandon'), false); // Test 40
console.log(annaLikes('Benjamin'), false); // Test 41
console.log(annaLikes('Samuel'), true); // Test 42
console.log(annaLikes('Frank'), false); // Test 43
console.log(annaLikes('Gregory'), false); // Test 44
console.log(annaLikes('Raymond'), false); // Test 45
console.log(annaLikes('Alexander'), false); // Test 46
console.log(annaLikes('Patrick'), false); // Test 47
console.log(annaLikes('Jack'), false); // Test 48
console.log(annaLikes('Dennis'), false); // Test 49
console.log(annaLikes('Jerry'), false); // Test 50
console.log(annaLikes('Tyler'), false); // Test 51
console.log(annaLikes('Aaron'), false); // Test 52
console.log(annaLikes('Jose'), true); // Test 53
console.log(annaLikes('Henry'), false); // Test 54
console.log(annaLikes('Adam'), true); // Test 55
console.log(annaLikes('Douglas'), false); // Test 56
console.log(annaLikes('Nathan'), false); // Test 57
console.log(annaLikes('Peter'), false); // Test 58
console.log(annaLikes('Zachary'), false); // Test 59
console.log(annaLikes('Kyle'), false); // Test 60
console.log(annaLikes('Walter'), false); // Test 61
console.log(annaLikes('Harold'), false); // Test 62
console.log(annaLikes('Jeremy'), false); // Test 63
console.log(annaLikes('Ethan'), false); // Test 64
console.log(annaLikes('Carl'), false); // Test 65
console.log(annaLikes('Keith'), false); // Test 66
console.log(annaLikes('Roger'), false); // Test 67
console.log(annaLikes('Gerald'), false); // Test 68
console.log(annaLikes('Christian'), false); // Test 69
console.log(annaLikes('Terry'), false); // Test 70
console.log(annaLikes('Sean'), true); // Test 71
console.log(annaLikes('Arthur'), false); // Test 72
console.log(annaLikes('Austin'), true); // Test 73
console.log(annaLikes('Noah'), true); // Test 74
console.log(annaLikes('Lawrence'), false); // Test 75
console.log(annaLikes('Jesse'), false); // Test 76
console.log(annaLikes('Joe'), false); // Test 77
console.log(annaLikes('Bryan'), false); // Test 78
console.log(annaLikes('Billy'), false); // Test 79
console.log(annaLikes('Jordan'), false); // Test 80
console.log(annaLikes('Albert'), false); // Test 81
console.log(annaLikes('Dylan'), false); // Test 82
console.log(annaLikes('Bruce'), false); // Test 83
console.log(annaLikes('Willie'), true); // Test 84
console.log(annaLikes('Gabriel'), false); // Test 85
console.log(annaLikes('Alan'), true); // Test 86
console.log(annaLikes('Juan'), true); // Test 87
console.log(annaLikes('Logan'), false); // Test 88
console.log(annaLikes('Wayne'), false); // Test 89
console.log(annaLikes('Ralph'), false); // Test 90
console.log(annaLikes('Roy'), false); // Test 91
console.log(annaLikes('Eugene'), false); // Test 92
console.log(annaLikes('Randy'), false); // Test 93
console.log(annaLikes('Vincent'), false); // Test 94
console.log(annaLikes('Russell'), false); // Test 95
console.log(annaLikes('Louis'), false); // Test 96
console.log(annaLikes('Philip'), false); // Test 97
console.log(annaLikes('Bobby'), false); // Test 98
console.log(annaLikes('Johnny'), false); // Test 99
console.log(annaLikes('Bradley'), false); // Test 100
