const longest7SegmentWord = (arr) => {
  const regex = /[kmvwx]/gi;
  const valid = arr.filter((el) => el.match(regex) === null);
  const longest = valid.sort((a, b) => b.length - a.length)[0];
  return longest ? longest : '';
};

// Tests
console.log(
  longest7SegmentWord(['knighthood', 'parental', 'fridge', 'clingfilm']),
  'parental'
);
console.log(
  longest7SegmentWord(['coding', 'crackers', 'edabit', 'celebration']),
  'celebration'
);
console.log(
  longest7SegmentWord(['velocity', 'mackerel', 'woven', 'kingsmen']),
  ''
);
console.log(
  longest7SegmentWord(['embarrassment', 'perceive', 'front']),
  'front'
);
// console.log(
//   longest7SegmentWord([
//     'truck',
//     'accessible',
//     'undermine',
//     'unique',
//     'tear',
//     'cat',
//     'avenue',
//     'labour',
//     'goat',
//     'dance',
//     'rise',
//     'scale',
//   ]),
//   'accessible'
// );
// console.log(
//   longest7SegmentWord([
//     'act',
//     'adjust',
//     'proud',
//     'battery',
//     'tear',
//     'beautiful',
//     'avenue',
//     'thoughtful',
//     'victory',
//     'mobile',
//     'straight',
//   ]),
//   'thoughtful'
// );
// console.log(longest7SegmentWord(['fair', 'tear', 'truck']), 'fair');
// console.log(
//   longest7SegmentWord(['scale', 'pass', 'act', 'sector', 'vain', 'scale']),
//   'sector'
// );
// console.log(
//   longest7SegmentWord([
//     'vegetarian',
//     'unique',
//     'sensitivity',
//     'goat',
//     'nature',
//     'attract',
//     'suntan',
//     'mobile',
//     'pillow',
//     'economist',
//     'arrest',
//     'galaxy',
//     'proud',
//     'proud',
//   ]),
//   'attract'
// );
// console.log(
//   longest7SegmentWord([
//     'vat',
//     'suntan',
//     'murder',
//     'dance',
//     'course',
//     'institution',
//   ]),
//   'institution'
// );
// console.log(
//   longest7SegmentWord([
//     'adjust',
//     'garlic',
//     'preoccupation',
//     'nature',
//     'garlic',
//     'undermine',
//     'pavement',
//     'payment',
//     'fair',
//     'twin',
//     'expertise',
//     'pillow',
//     'dance',
//     'economist',
//     'establish',
//     'nervous',
//     'sector',
//   ]),
//   'preoccupation'
// );
// console.log(
//   longest7SegmentWord([
//     'embarrassment',
//     'bell',
//     'obese',
//     'width',
//     'singer',
//     'strikebreaker',
//     'width',
//     'preoccupation',
//     'nervous',
//   ]),
//   'preoccupation'
// );
// console.log(longest7SegmentWord(['winner', 'twin', 'establish']), 'establish');
// console.log(
//   longest7SegmentWord([
//     'fair',
//     'institution',
//     'vegetarian',
//     'electron',
//     'suntan',
//     'settle',
//     'royalty',
//     'bracket',
//     'conductor',
//     'blade',
//     'camp',
//     'potential',
//     'human body',
//   ]),
//   'institution'
// );
// console.log(
//   longest7SegmentWord([
//     'width',
//     'straight',
//     'sign',
//     'inspire',
//     'lay',
//     'pavement',
//     'settle',
//     'undermine',
//     'cat',
//     'labour',
//     'adjust',
//     'admire',
//     'scramble',
//     'pavement',
//     'limited',
//     'payment',
//     'withdrawal',
//     'full',
//     'brave',
//   ]),
//   'straight'
// );
// console.log(
//   longest7SegmentWord([
//     'limited',
//     'arrest',
//     'harm',
//     'tear',
//     'vain',
//     'bracket',
//     'settle',
//     'settle',
//     'spine',
//     'mobile',
//     'potential',
//     'cat',
//     'winner',
//     'tear',
//   ]),
//   'potential'
// );
// console.log(
//   longest7SegmentWord(['front', 'economist', 'sector', 'camp']),
//   'sector'
// );
// console.log(
//   longest7SegmentWord([
//     'murder',
//     'vain',
//     'fair',
//     'sign',
//     'establish',
//     'flow',
//     'bell',
//     'truck',
//     'winner',
//     'tear',
//     'avenue',
//     'move',
//     'pillow',
//     'murder',
//     'gesture',
//     'garlic',
//     'unique',
//     'brave',
//     'pass',
//     'avenue',
//   ]),
//   'establish'
// );
// console.log(
//   longest7SegmentWord([
//     'full',
//     'suntan',
//     'strikebreaker',
//     'front',
//     'truck',
//     'vegetarian',
//     'maze',
//     'shine',
//     'potential',
//     'conductor',
//     'width',
//     'economist',
//     'lounge',
//     'pound',
//     'camp',
//     'sensitivity',
//   ]),
//   'potential'
// );
// console.log(
//   longest7SegmentWord([
//     'party',
//     'width',
//     'sector',
//     'withdrawal',
//     'limited',
//     'victory',
//     'presidency',
//     'pillow',
//     'beautiful',
//     'shine',
//   ]),
//   'presidency'
// );
// console.log(
//   longest7SegmentWord([
//     'front',
//     'mirror',
//     'shine',
//     'spine',
//     'lay',
//     'obese',
//     'shine',
//     'singer',
//     'straight',
//     'establish',
//     'embarrassment',
//     'admire',
//     'vain',
//     'presidency',
//     'winner',
//     'dance',
//     'inject',
//     'proud',
//     'establish',
//   ]),
//   'presidency'
// );
// console.log(
//   longest7SegmentWord([
//     'pound',
//     'scramble',
//     'labour',
//     'vegetarian',
//     'obese',
//     'delicate',
//     'dictionary',
//     'act',
//     'nature',
//     'shine',
//   ]),
//   'dictionary'
// );
// console.log(
//   longest7SegmentWord([
//     'goat',
//     'institution',
//     'move',
//     'twin',
//     'lay',
//     'embarrassment',
//     'labour',
//   ]),
//   'institution'
// );
// console.log(
//   longest7SegmentWord([
//     'victory',
//     'embarrassment',
//     'truck',
//     'presidency',
//     'maze',
//     'truck',
//   ]),
//   'presidency'
// );
// console.log(
//   longest7SegmentWord([
//     'accessible',
//     'embarrassment',
//     'embarrassment',
//     'extort',
//     'width',
//     'garlic',
//   ]),
//   'accessible'
// );
// console.log(longest7SegmentWord(['shine', 'admire']), 'shine');
// console.log(
//   longest7SegmentWord([
//     'sector',
//     'conductor',
//     'arrest',
//     'inspire',
//     'harm',
//     'grain',
//     'tear',
//     'vat',
//     'shine',
//     'course',
//     'admire',
//     'shine',
//     'attract',
//     'victory',
//   ]),
//   'conductor'
// );
// console.log(
//   longest7SegmentWord([
//     'rise',
//     'dance',
//     'dance',
//     'undermine',
//     'vain',
//     'blade',
//     'pillow',
//     'economist',
//     'freight',
//     'goat',
//     'pavement',
//   ]),
//   'freight'
// );
// console.log(
//   longest7SegmentWord([
//     'institution',
//     'pillow',
//     'straight',
//     'suntan',
//     'presidency',
//     'exception',
//     'expertise',
//     'sensitivity',
//   ]),
//   'institution'
// );
// console.log(
//   longest7SegmentWord([
//     'grain',
//     'fair',
//     'settle',
//     'thoughtful',
//     'vain',
//     'admire',
//     'sign',
//   ]),
//   'thoughtful'
// );
// console.log(
//   longest7SegmentWord([
//     'presidency',
//     'bracket',
//     'flavor',
//     'payment',
//     'nervous',
//     'extort',
//     'sector',
//     'garlic',
//     'limited',
//   ]),
//   'presidency'
// );
// console.log(
//   longest7SegmentWord([
//     'twin',
//     'pillow',
//     'blade',
//     'mobile',
//     'royalty',
//     'undermine',
//     'lay',
//     'front',
//     'fair',
//     'flow',
//     'party',
//     'withdrawal',
//     'sign',
//     'scramble',
//     'accessible',
//     'vain',
//   ]),
//   'accessible'
// );
// console.log(
//   longest7SegmentWord([
//     'labour',
//     'pass',
//     'camp',
//     'vegetarian',
//     'freight',
//     'victory',
//     'avenue',
//     'flow',
//     'garlic',
//     'gesture',
//     'nervous',
//     'vat',
//     'preoccupation',
//     'maze',
//     'arrest',
//     'camp',
//     'dictionary',
//     'inspire',
//   ]),
//   'preoccupation'
// );
// console.log(
//   longest7SegmentWord([
//     'vegetarian',
//     'expertise',
//     'straight',
//     'harm',
//     'course',
//     'network',
//     'preoccupation',
//     'cat',
//     'extort',
//     'full',
//     'limited',
//     'flex',
//     'unique',
//     'singer',
//     'avenue',
//     'establish',
//     'bracket',
//     'mobile',
//   ]),
//   'preoccupation'
// );
// console.log(
//   longest7SegmentWord([
//     'admire',
//     'scale',
//     'goat',
//     'vat',
//     'rise',
//     'attract',
//     'vegetarian',
//     'economist',
//     'admire',
//     'act',
//     'flavor',
//     'flow',
//     'preoccupation',
//   ]),
//   'preoccupation'
// );
// console.log(
//   longest7SegmentWord([
//     'shine',
//     'scale',
//     'freight',
//     'extort',
//     'withdrawal',
//     'suntan',
//     'grain',
//     'preoccupation',
//     'arrest',
//     'habit',
//     'party',
//     'habit',
//     'sign',
//     'electron',
//     'harm',
//     'grain',
//     'rise',
//     'gesture',
//     'chimney',
//   ]),
//   'preoccupation'
// );
// console.log(
//   longest7SegmentWord([
//     'beautiful',
//     'victory',
//     'electron',
//     'goat',
//     'proud',
//     'preoccupation',
//     'nature',
//     'network',
//     'proud',
//     'full',
//     'sensitivity',
//     'royalty',
//     'dance',
//     'scramble',
//   ]),
//   'preoccupation'
// );
// console.log(
//   longest7SegmentWord([
//     'vain',
//     'nature',
//     'garlic',
//     'garlic',
//     'inspire',
//     'thoughtful',
//     'winner',
//     'blade',
//     'pillow',
//     'fair',
//     'goat',
//     'bell',
//     'lounge',
//     'fair',
//   ]),
//   'thoughtful'
// );
// console.log(
//   longest7SegmentWord([
//     'expertise',
//     'payment',
//     'exception',
//     'attract',
//     'habit',
//     'institution',
//     'embarrassment',
//     'pavement',
//     'accessible',
//     'accessible',
//     'bell',
//     'perceive',
//     'scale',
//   ]),
//   'institution'
// );
// console.log(
//   longest7SegmentWord([
//     'spine',
//     'presidency',
//     'scale',
//     'goat',
//     'beautiful',
//     'harm',
//     'flavor',
//     'proud',
//     'limited',
//     'battery',
//     'unique',
//     'scramble',
//     'pound',
//     'nature',
//     'flavor',
//     'avenue',
//     'pound',
//   ]),
//   'presidency'
// );
// console.log(
//   longest7SegmentWord([
//     'institution',
//     'sign',
//     'pass',
//     'cat',
//     'cook',
//     'nervous',
//     'habit',
//     'accessible',
//     'nervous',
//     'lounge',
//     'unique',
//     'undermine',
//     'royalty',
//     'chimney',
//     'obese',
//     'bracket',
//     'habit',
//     'potential',
//     'sector',
//   ]),
//   'institution'
// );
// console.log(
//   longest7SegmentWord([
//     'galaxy',
//     'presidency',
//     'camp',
//     'pillow',
//     'labour',
//     'pass',
//     'pillow',
//     'suntan',
//     'payment',
//     'economist',
//     'unique',
//   ]),
//   'presidency'
// );
// console.log(
//   longest7SegmentWord([
//     'maze',
//     'human body',
//     'move',
//     'perceive',
//     'maze',
//     'scramble',
//     'flavor',
//     'delicate',
//     'accessible',
//   ]),
//   'accessible'
// );
// console.log(
//   longest7SegmentWord([
//     'freight',
//     'limited',
//     'straight',
//     'settle',
//     'obese',
//     'shy',
//     'establish',
//     'galaxy',
//     'avenue',
//     'victory',
//     'proud',
//     'dictionary',
//     'conductor',
//     'spine',
//     'pillow',
//     'economist',
//     'habit',
//     'royalty',
//     'strikebreaker',
//     'winner',
//   ]),
//   'dictionary'
// );
// console.log(
//   longest7SegmentWord([
//     'vegetarian',
//     'labour',
//     'course',
//     'grain',
//     'freight',
//     'pavement',
//     'nervous',
//     'unique',
//     'mirror',
//     'galaxy',
//     'beautiful',
//     'winner',
//     'winner',
//     'cat',
//     'pillow',
//     'spine',
//     'course',
//     'murder',
//     'pavement',
//     'withdrawal',
//   ]),
//   'beautiful'
// );
// console.log(
//   longest7SegmentWord([
//     'vat',
//     'mirror',
//     'winner',
//     'human body',
//     'potential',
//     'front',
//   ]),
//   'potential'
// );
// console.log(
//   longest7SegmentWord([
//     'blade',
//     'victory',
//     'thoughtful',
//     'undermine',
//     'royalty',
//     'nature',
//     'pillow',
//   ]),
//   'thoughtful'
// );
// console.log(
//   longest7SegmentWord([
//     'electron',
//     'act',
//     'blade',
//     'bell',
//     'straight',
//     'extort',
//     'battery',
//     'maze',
//     'galaxy',
//     'act',
//     'embarrassment',
//   ]),
//   'electron'
// );
// console.log(
//   longest7SegmentWord([
//     'network',
//     'potential',
//     'maze',
//     'move',
//     'chimney',
//     'straight',
//     'party',
//     'thoughtful',
//     'freight',
//     'obese',
//     'dance',
//     'inspire',
//     'proud',
//     'harm',
//     'human body',
//     'strikebreaker',
//   ]),
//   'thoughtful'
// );
// console.log(
//   longest7SegmentWord([
//     'course',
//     'galaxy',
//     'garlic',
//     'pillow',
//     'camp',
//     'brave',
//     'extort',
//     'conductor',
//     'mirror',
//     'full',
//     'goat',
//     'twin',
//     'cat',
//   ]),
//   'conductor'
// );
// console.log(
//   longest7SegmentWord([
//     'inject',
//     'sensitivity',
//     'party',
//     'withdrawal',
//     'establish',
//     'potential',
//     'rise',
//     'presidency',
//     'galaxy',
//     'tear',
//     'party',
//     'vegetarian',
//     'economist',
//     'cat',
//     'maze',
//     'truck',
//     'lounge',
//     'conductor',
//   ]),
//   'presidency'
// );
// console.log(
//   longest7SegmentWord([
//     'spine',
//     'sign',
//     'vegetarian',
//     'victory',
//     'inject',
//     'flex',
//     'embarrassment',
//     'accessible',
//     'battery',
//     'network',
//     'avenue',
//     'singer',
//     'lay',
//     'move',
//   ]),
//   'accessible'
// );
// console.log(
//   longest7SegmentWord(['extort', 'galaxy', 'garlic', 'winner']),
//   'garlic'
// );
