// https://edabit.com/challenge/jNanQ3zKkCdA9ANJw

const wiggleString = (s) => {
  let spaces = 0;
  const words = [];

  for (let i = 0; i < s.length * 2 + 1; i++) {
    words.push(`${' '.repeat(spaces)}${s}`);
    if (i >= s.length) {
      spaces--;
    } else {
      spaces++;
    }
  }

  return words;
};

// Tests

console.log(wiggleString('hello'), [
  'hello',
  ' hello',
  '  hello',
  '   hello',
  '    hello',
  '     hello',
  '    hello',
  '   hello',
  '  hello',
  ' hello',
  'hello',
]);

console.log(wiggleString('EDABIT'), [
  'EDABIT',
  ' EDABIT',
  '  EDABIT',
  '   EDABIT',
  '    EDABIT',
  '     EDABIT',
  '      EDABIT',
  '     EDABIT',
  '    EDABIT',
  '   EDABIT',
  '  EDABIT',
  ' EDABIT',
  'EDABIT',
]);

console.log(wiggleString('Wiggle Time'), [
  'Wiggle Time',
  ' Wiggle Time',
  '  Wiggle Time',
  '   Wiggle Time',
  '    Wiggle Time',
  '     Wiggle Time',
  '      Wiggle Time',
  '       Wiggle Time',
  '        Wiggle Time',
  '         Wiggle Time',
  '          Wiggle Time',
  '           Wiggle Time',
  '          Wiggle Time',
  '         Wiggle Time',
  '        Wiggle Time',
  '       Wiggle Time',
  '      Wiggle Time',
  '     Wiggle Time',
  '    Wiggle Time',
  '   Wiggle Time',
  '  Wiggle Time',
  ' Wiggle Time',
  'Wiggle Time',
]);

console.log(wiggleString('the dog'), [
  'the dog',
  ' the dog',
  '  the dog',
  '   the dog',
  '    the dog',
  '     the dog',
  '      the dog',
  '       the dog',
  '      the dog',
  '     the dog',
  '    the dog',
  '   the dog',
  '  the dog',
  ' the dog',
  'the dog',
]);
console.log(wiggleString('wiggle wiggle wiggle'), [
  'wiggle wiggle wiggle',
  ' wiggle wiggle wiggle',
  '  wiggle wiggle wiggle',
  '   wiggle wiggle wiggle',
  '    wiggle wiggle wiggle',
  '     wiggle wiggle wiggle',
  '      wiggle wiggle wiggle',
  '       wiggle wiggle wiggle',
  '        wiggle wiggle wiggle',
  '         wiggle wiggle wiggle',
  '          wiggle wiggle wiggle',
  '           wiggle wiggle wiggle',
  '            wiggle wiggle wiggle',
  '             wiggle wiggle wiggle',
  '              wiggle wiggle wiggle',
  '               wiggle wiggle wiggle',
  '                wiggle wiggle wiggle',
  '                 wiggle wiggle wiggle',
  '                  wiggle wiggle wiggle',
  '                   wiggle wiggle wiggle',
  '                    wiggle wiggle wiggle',
  '                   wiggle wiggle wiggle',
  '                  wiggle wiggle wiggle',
  '                 wiggle wiggle wiggle',
  '                wiggle wiggle wiggle',
  '               wiggle wiggle wiggle',
  '              wiggle wiggle wiggle',
  '             wiggle wiggle wiggle',
  '            wiggle wiggle wiggle',
  '           wiggle wiggle wiggle',
  '          wiggle wiggle wiggle',
  '         wiggle wiggle wiggle',
  '        wiggle wiggle wiggle',
  '       wiggle wiggle wiggle',
  '      wiggle wiggle wiggle',
  '     wiggle wiggle wiggle',
  '    wiggle wiggle wiggle',
  '   wiggle wiggle wiggle',
  '  wiggle wiggle wiggle',
  ' wiggle wiggle wiggle',
  'wiggle wiggle wiggle',
]);
console.log(wiggleString('Hello World!'), [
  'Hello World!',
  ' Hello World!',
  '  Hello World!',
  '   Hello World!',
  '    Hello World!',
  '     Hello World!',
  '      Hello World!',
  '       Hello World!',
  '        Hello World!',
  '         Hello World!',
  '          Hello World!',
  '           Hello World!',
  '            Hello World!',
  '           Hello World!',
  '          Hello World!',
  '         Hello World!',
  '        Hello World!',
  '       Hello World!',
  '      Hello World!',
  '     Hello World!',
  '    Hello World!',
  '   Hello World!',
  '  Hello World!',
  ' Hello World!',
  'Hello World!',
]);
console.log(wiggleString('Edabit is fun!'), [
  'Edabit is fun!',
  ' Edabit is fun!',
  '  Edabit is fun!',
  '   Edabit is fun!',
  '    Edabit is fun!',
  '     Edabit is fun!',
  '      Edabit is fun!',
  '       Edabit is fun!',
  '        Edabit is fun!',
  '         Edabit is fun!',
  '          Edabit is fun!',
  '           Edabit is fun!',
  '            Edabit is fun!',
  '             Edabit is fun!',
  '              Edabit is fun!',
  '             Edabit is fun!',
  '            Edabit is fun!',
  '           Edabit is fun!',
  '          Edabit is fun!',
  '         Edabit is fun!',
  '        Edabit is fun!',
  '       Edabit is fun!',
  '      Edabit is fun!',
  '     Edabit is fun!',
  '    Edabit is fun!',
  '   Edabit is fun!',
  '  Edabit is fun!',
  ' Edabit is fun!',
  'Edabit is fun!',
]);
console.log(wiggleString('123456789'), [
  '123456789',
  ' 123456789',
  '  123456789',
  '   123456789',
  '    123456789',
  '     123456789',
  '      123456789',
  '       123456789',
  '        123456789',
  '         123456789',
  '        123456789',
  '       123456789',
  '      123456789',
  '     123456789',
  '    123456789',
  '   123456789',
  '  123456789',
  ' 123456789',
  '123456789',
]);
console.log(wiggleString('qwertyuiop'), [
  'qwertyuiop',
  ' qwertyuiop',
  '  qwertyuiop',
  '   qwertyuiop',
  '    qwertyuiop',
  '     qwertyuiop',
  '      qwertyuiop',
  '       qwertyuiop',
  '        qwertyuiop',
  '         qwertyuiop',
  '          qwertyuiop',
  '         qwertyuiop',
  '        qwertyuiop',
  '       qwertyuiop',
  '      qwertyuiop',
  '     qwertyuiop',
  '    qwertyuiop',
  '   qwertyuiop',
  '  qwertyuiop',
  ' qwertyuiop',
  'qwertyuiop',
]);
console.log(wiggleString('python javascript'), [
  'python javascript',
  ' python javascript',
  '  python javascript',
  '   python javascript',
  '    python javascript',
  '     python javascript',
  '      python javascript',
  '       python javascript',
  '        python javascript',
  '         python javascript',
  '          python javascript',
  '           python javascript',
  '            python javascript',
  '             python javascript',
  '              python javascript',
  '               python javascript',
  '                python javascript',
  '                 python javascript',
  '                python javascript',
  '               python javascript',
  '              python javascript',
  '             python javascript',
  '            python javascript',
  '           python javascript',
  '          python javascript',
  '         python javascript',
  '        python javascript',
  '       python javascript',
  '      python javascript',
  '     python javascript',
  '    python javascript',
  '   python javascript',
  '  python javascript',
  ' python javascript',
  'python javascript',
]);
